#!/bin/bash

usage()
{
    cmd=`basename $0`
    echo "usage:$cmd [-s]"
    exit 0
}

if [ $# -gt 1 ];then
    usage
fi

skip_bundle=0
if [ "$1" = "-s" ];then
    skip_bundle=1
fi

os=`uname -s`
if [ $os = 'Linux' ];then
    vimrc=/etc/vimrc
elif [ $os = 'Darwin' ];then
    vimrc=~/.vimrc
fi

# test vim installed
vim --version > /dev/null 2>&1
if [ $? -ne 0 ];then
    echo "vim not installed!!!"
    exit 1
fi

MYVIM_PATH=/usr/local/myvim
MYVIM_MAIN=$MYVIM_PATH/'vim.main'
if [ ! -d $MYVIM_PATH ];then
    mkdir -p $MYVIM_PATH
fi

cp -rf ./vim.main $MYVIM_PATH/
cp -rf ./bundles  $MYVIM_PATH/
cp -rf ./base     $MYVIM_PATH/
cp -rf ./coding   $MYVIM_PATH/

mkdir -p /usr/local/include/ycm_include
mkdir -p ~/.vim
cp -rf ./tmpl/ycm_extra_conf.py ~/.vim/ycm_extra_conf.py
if [ $os = 'Darwin' ];then
    cp -rf /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/* /usr/local/include
fi
cp -rf ./ycmconf /usr/local/bin/

grep "^source $MYVIM_MAIN$" $vimrc > /dev/null 2>&1
if [ $? -ne 0 ];then
    echo "source $MYVIM_MAIN" >> $vimrc
fi

if [ ! -d $MYVIM_PATH/bundles/vundle ];then
    git clone https://github.com/VundleVim/Vundle.vim.git $MYVIM_PATH/bundles/vundle || exit 1
fi

if [ $skip_bundle -eq 0 ];then
    vim +BundleUpdate +qall || exit 1
fi

if [ $skip_bundle -eq 0 ];then
    if [ $os = 'Linux' ];then
        yum install -y the_silver_searcher
        yum install -y ctags
        yum install -y cmake
    elif [ $os = 'Darwin' ];then
        brew install the_silver_searcher
        brew install ctags
        brew install cmake
    fi
fi

if [ ! -f /usr/local/myvim/bundles/YouCompleteMe/third_party/ycmd/ycm_core.so ];then
    /usr/local/myvim/bundles/YouCompleteMe/install.sh --clang-completer
fi

