#!/bin/bash

usage()
{
    cmd=`basename $0`
    echo "usage:$cmd"
    exit 0
}

if [ $# -ne 0 ];then
    usage
fi

# test vim installed
vim --version > /dev/null 2>&1
if [ $? -ne 0 ];then
    echo "vim not installed!!!"
    exit 1
fi

MYVIM_PATH=/usr/local/myvim
MYVIM_MAIN=$MYVIM_PATH/'vim.main'
if [ ! -d $MYVIM_PATH ];then
    mkdir -p $MYVIM_PATH
fi

cp -rf ./vim.main $MYVIM_PATH/
cp -rf ./bundles  $MYVIM_PATH/
cp -rf ./base     $MYVIM_PATH/
cp -rf ./coding   $MYVIM_PATH/

grep "^source $MYVIM_MAIN$" ~/.vimrc > /dev/null 2>&1
if [ $? -ne 0 ];then
    echo "source $MYVIM_MAIN" >> ~/.vimrc
fi

if [ ! -d $MYVIM_PATH/bundles/vundle ];then
    git clone https://github.com/VundleVim/Vundle.vim.git $MYVIM_PATH/bundles/vundle || exit 1
fi

vim +BundleUpdate +qall || exit 1

os=`uname -s`
if [ $os = 'Linux' ];then
    yum install -y ctags || exit 1
    yum install -y cmake || exit 1
elif [ $os = 'Darwin' ];then
    brew install ctags || exit 1
    brew install cmake || exit 1
fi

if [ ! -f /usr/local/myvim/bundles/YouCompleteMe/third_party/ycmd/ycm_core.so ];then
    /usr/local/myvim/bundles/YouCompleteMe/install.sh --clang-completer
fi

